name: Java CI

on: [push, pull_request]


jobs:
  gradle:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: JDK environment setup
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'adopt-hotspot'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build Artifact with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Release the artifact into Github Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        files: |
            build/distributions/*

